services:
  api:
    build:
      context: ../../backend-go
      dockerfile: Dockerfile
    container_name: philmymeds-api
    ports:
      - "8080:8081"
    env_file:
      - ../../.env
   
    environment:
      - PORT=${API_PORT:-8081} 
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin #27017 is the container port for mongodb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-sanjeev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-philmymedspg}
      - POSTGRES_SSLMODE=disable
    depends_on:
      - mongodb
      - postgres
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: philmymeds-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  postgres: 
    image: postgres:15
    container_name: philmymeds-postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sanjeev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-philmymedspg}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  mongodb_data:
  postgres_data:
