POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "fullName": "John Doe",
    "email": "john@example.com",
    "password": "password",
    "profileImageUrl": ""
}
###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "password"
}
###
GET http://localhost:8000/api/auth/getUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTIxZGIyYzMxYWI1MjdmZGMwNTAxNCIsImlhdCI6MTc1NDQwNzM2MCwiZXhwIjoxNzU0NDEwOTYwfQ.Vze3EgmwphFgfZwDGR-jqKoje5v2baUSH3tV-D2okDQ
###
POST http://localhost:8000/api/income/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTIxZGIyYzMxYWI1MjdmZGMwNTAxNCIsImlhdCI6MTc1NDQwNzM2MCwiZXhwIjoxNzU0NDEwOTYwfQ.Vze3EgmwphFgfZwDGR-jqKoje5v2baUSH3tV-D2okDQ

{
    "icon": "💰",
    "source": "Salary",
    "amount": 1000,
    "date": "2025-08-05"
}
###
GET http://localhost:8000/api/income/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTIxZGIyYzMxYWI1MjdmZGMwNTAxNCIsImlhdCI6MTc1NDQwNzM2MCwiZXhwIjoxNzU0NDEwOTYwfQ.Vze3EgmwphFgfZwDGR-jqKoje5v2baUSH3tV-D2okDQ
###
DELETE http://localhost:8000/api/income/68921e000000000000000000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTIxZGIyYzMxYWI1MjdmZGMwNTAxNCIsImlhdCI6MTc1NDQwNzM2MCwiZXhwIjoxNzU0NDEwOTYwfQ.Vze3EgmwphFgfZwDGR-jqKoje5v2baUSH3tV-D2okDQ
###
GET http://localhost:8000/api/income/downloadexcel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTIxZGIyYzMxYWI1MjdmZGMwNTAxNCIsImlhdCI6MTc1NDQwNzM2MCwiZXhwIjoxNzU0NDEwOTYwfQ.Vze3EgmwphFgfZwDGR-jqKoje5v2baUSH3tV-D2okDQ