### 
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "firstName": "muskan",
  "lastName": "lama",
  "username": "muskanlama",
  "email": "testing@gmail.com",
  "password": "Password123!2"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "muskanlama",
  "email": "testing@gmail.com",
  "password": "Password123!2"
}