###
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe", 
    "username": "johndoe",
    "email": "john@example.com",
    "password": "password123"
}

###
GET http://localhost:5000/api/users

###
GET http://localhost:5000/api/users/6857fb95e270695cd085cbe6
