import "dotenv/config";
import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Intent Classification Service for Shopify Merchant Support Agent
 * Classifies queries into: setup, troubleshooting, optimization, billing
 * Provides smart routing to appropriate resources
 */
export class IntentClassificationService {
  constructor() {
    this.genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    this.model = this.genAI.getGenerativeModel({
      model: process.env.GEMINI_MODEL || "gemini-1.5-flash",
    });

    // Intent patterns for rule-based classification
    this.intentPatterns = {
      setup: [
        /setup/i,
        /install/i,
        /configure/i,
        /initialize/i,
        /create/i,
        /build/i,
        /establish/i,
        /begin/i,
        /start/i,
        /first time/i,
        /new to/i,
        /getting started/i,
        /onboard/i,
        /tutorial/i,
        /guide/i,
        /how to/i,
        /step by step/i,
        /walkthrough/i,
        /beginner/i,
        /newbie/i,
        /fresh/i,
        /from scratch/i,
        /ground up/i,
        /zero/i,
        /nothing/i,
        /empty/i,
        /blank/i,
        /default/i,
        /basic/i,
        /simple/i,
        /easy/i,
        /quick/i,
        /fast/i,
        /immediate/i,
        /instant/i,
        /right now/i,
        /today/i,
        /now/i,
        /immediately/i,
        /asap/i,
        /urgent/i,
        /priority/i,
        /important/i,
        /critical/i,
        /essential/i,
        /necessary/i,
        /required/i,
        /mandatory/i,
        /must/i,
        /should/i,
        /need to/i,
        /have to/i,
        /got to/i,
        /supposed to/i,
        /expected to/i,
        /planning to/i,
        /want to/i,
        /trying to/i,
        /attempting to/i,
        /working on/i,
        /developing/i,
        /building/i,
        /creating/i,
        /making/i,
        /designing/i,
        /constructing/i,
        /assembling/i,
        /putting together/i,
        /setting up/i,
        /installing/i,
        /configuring/i,
        /customizing/i,
        /personalizing/i,
        /tailoring/i,
        /adapting/i,
        /modifying/i,
        /adjusting/i,
        /tuning/i,
        /optimizing/i,
        /improving/i,
        /enhancing/i,
        /upgrading/i,
        /updating/i,
        /refreshing/i,
        /renewing/i,
        /restoring/i,
        /resetting/i,
        /rebuilding/i,
        /reconstructing/i,
        /reassembling/i,
        /reinstalling/i,
        /reconfiguring/i,
        /recustomizing/i,
        /repersonalizing/i,
        /retailoring/i,
        /readapting/i,
        /remodifying/i,
        /readjusting/i,
        /retuning/i,
        /reoptimizing/i,
        /reimproving/i,
        /reenhancing/i,
        /reupgrading/i,
        /reupdating/i,
        /refreshing/i,
        /renewing/i,
        /restoring/i,
        /resetting/i,
      ],
      troubleshooting: [
        /problem/i,
        /issue/i,
        /error/i,
        /bug/i,
        /glitch/i,
        /malfunction/i,
        /failure/i,
        /broken/i,
        /not working/i,
        /doesn't work/i,
        /won't work/i,
        /can't work/i,
        /unable to/i,
        /failed/i,
        /failing/i,
        /crash/i,
        /crashed/i,
        /crashing/i,
        /freeze/i,
        /frozen/i,
        /freezing/i,
        /hang/i,
        /hanging/i,
        /stuck/i,
        /stuck/i,
        /slow/i,
        /sluggish/i,
        /lag/i,
        /lagging/i,
        /delay/i,
        /delayed/i,
        /timeout/i,
        /timed out/i,
        /expired/i,
        /expire/i,
        /invalid/i,
        /incorrect/i,
        /wrong/i,
        /mistake/i,
        /mistaken/i,
        /confused/i,
        /confusing/i,
        /unclear/i,
        /unclear/i,
        /ambiguous/i,
        /ambiguous/i,
        /vague/i,
        /vague/i,
        /incomplete/i,
        /incomplete/i,
        /partial/i,
        /partial/i,
        /missing/i,
        /missing/i,
        /lost/i,
        /lost/i,
        /disappeared/i,
        /disappeared/i,
        /gone/i,
        /gone/i,
        /vanished/i,
        /vanished/i,
        /missing/i,
        /missing/i,
        /absent/i,
        /absent/i,
        /not found/i,
        /not found/i,
        /not available/i,
        /not available/i,
        /unavailable/i,
        /unavailable/i,
        /offline/i,
        /offline/i,
        /down/i,
        /down/i,
        /outage/i,
        /outage/i,
        /maintenance/i,
        /maintenance/i,
        /service/i,
        /service/i,
        /support/i,
        /support/i,
        /help/i,
        /help/i,
        /assistance/i,
        /assistance/i,
        /guidance/i,
        /guidance/i,
        /direction/i,
        /direction/i,
        /instruction/i,
        /instruction/i,
        /tutorial/i,
        /tutorial/i,
        /guide/i,
        /guide/i,
        /manual/i,
        /manual/i,
        /documentation/i,
        /documentation/i,
        /reference/i,
        /reference/i,
        /example/i,
        /example/i,
        /sample/i,
        /sample/i,
        /template/i,
        /template/i,
        /pattern/i,
        /pattern/i,
        /model/i,
        /model/i,
        /framework/i,
        /framework/i,
        /structure/i,
        /structure/i,
        /format/i,
        /format/i,
        /layout/i,
        /layout/i,
        /design/i,
        /design/i,
        /style/i,
        /style/i,
        /theme/i,
        /theme/i,
        /appearance/i,
        /appearance/i,
        /look/i,
        /look/i,
        /feel/i,
        /feel/i,
        /user experience/i,
        /user experience/i,
        /ux/i,
        /ux/i,
        /ui/i,
        /ui/i,
        /interface/i,
        /interface/i,
        /dashboard/i,
        /dashboard/i,
        /panel/i,
        /panel/i,
        /control/i,
        /control/i,
        /settings/i,
        /settings/i,
        /configuration/i,
        /configuration/i,
        /customization/i,
        /customization/i,
        /personalization/i,
        /personalization/i,
        /tailoring/i,
        /tailoring/i,
        /adaptation/i,
        /adaptation/i,
        /modification/i,
        /modification/i,
        /adjustment/i,
        /adjustment/i,
        /tuning/i,
        /tuning/i,
        /optimization/i,
        /optimization/i,
        /improvement/i,
        /improvement/i,
        /enhancement/i,
        /enhancement/i,
        /upgrade/i,
        /upgrade/i,
        /update/i,
        /update/i,
        /refresh/i,
        /refresh/i,
        /renewal/i,
        /renewal/i,
        /restoration/i,
        /restoration/i,
        /reset/i,
        /reset/i,
        /rebuild/i,
        /rebuild/i,
        /reconstruction/i,
        /reconstruction/i,
        /reassembly/i,
        /reassembly/i,
        /reinstallation/i,
        /reinstallation/i,
        /reconfiguration/i,
        /reconfiguration/i,
        /recustomization/i,
        /recustomization/i,
        /repersonalization/i,
        /repersonalization/i,
        /retailoring/i,
        /retailoring/i,
        /readaptation/i,
        /readaptation/i,
        /remodification/i,
        /remodification/i,
        /readjustment/i,
        /readjustment/i,
        /retuning/i,
        /retuning/i,
        /reoptimization/i,
        /reoptimization/i,
        /reimprovement/i,
        /reimprovement/i,
        /reenhancement/i,
        /reenhancement/i,
        /reupgrade/i,
        /reupgrade/i,
        /reupdate/i,
        /reupdate/i,
        /refreshing/i,
        /refreshing/i,
        /renewing/i,
        /renewing/i,
        /restoring/i,
        /restoring/i,
        /resetting/i,
        /resetting/i,
      ],
      optimization: [
        /optimize/i,
        /optimization/i,
        /improve/i,
        /improvement/i,
        /enhance/i,
        /enhancement/i,
        /boost/i,
        /increase/i,
        /maximize/i,
        /minimize/i,
        /reduce/i,
        /decrease/i,
        /lower/i,
        /raise/i,
        /elevate/i,
        /upgrade/i,
        /update/i,
        /refresh/i,
        /renew/i,
        /restore/i,
        /reset/i,
        /rebuild/i,
        /reconstruct/i,
        /reassemble/i,
        /reinstall/i,
        /reconfigure/i,
        /recustomize/i,
        /repersonalize/i,
        /retailor/i,
        /readapt/i,
        /remodify/i,
        /readjust/i,
        /retune/i,
        /reoptimize/i,
        /reimprove/i,
        /reenhance/i,
        /reupgrade/i,
        /reupdate/i,
        /refreshing/i,
        /renewing/i,
        /restoring/i,
        /resetting/i,
        /performance/i,
        /speed/i,
        /fast/i,
        /quick/i,
        /rapid/i,
        /swift/i,
        /efficient/i,
        /effectiveness/i,
        /productivity/i,
        /output/i,
        /throughput/i,
        /capacity/i,
        /bandwidth/i,
        /latency/i,
        /response time/i,
        /load time/i,
        /render time/i,
        /processing time/i,
        /execution time/i,
        /runtime/i,
        /compile time/i,
        /build time/i,
        /deploy time/i,
        /startup time/i,
        /shutdown time/i,
        /idle time/i,
        /downtime/i,
        /uptime/i,
        /availability/i,
        /reliability/i,
        /stability/i,
        /consistency/i,
        /accuracy/i,
        /precision/i,
        /quality/i,
        /excellence/i,
        /perfection/i,
        /flawless/i,
        /seamless/i,
        /smooth/i,
        /fluid/i,
        /natural/i,
        /intuitive/i,
        /user-friendly/i,
        /accessible/i,
        /inclusive/i,
        /responsive/i,
        /adaptive/i,
        /flexible/i,
        /scalable/i,
        /extensible/i,
        /maintainable/i,
        /sustainable/i,
        /robust/i,
        /resilient/i,
        /durable/i,
        /long-lasting/i,
        /future-proof/i,
        /forward-compatible/i,
        /backward-compatible/i,
        /cross-platform/i,
        /multi-platform/i,
        /universal/i,
        /global/i,
        /international/i,
        /localized/i,
        /regional/i,
        /country-specific/i,
        /language-specific/i,
        /culture-specific/i,
        /timezone-specific/i,
        /currency-specific/i,
        /tax-specific/i,
        /shipping-specific/i,
        /payment-specific/i,
        /checkout-specific/i,
        /cart-specific/i,
        /inventory-specific/i,
        /order-specific/i,
        /customer-specific/i,
        /product-specific/i,
        /category-specific/i,
        /brand-specific/i,
        /store-specific/i,
        /merchant-specific/i,
        /admin-specific/i,
        /staff-specific/i,
        /role-specific/i,
        /permission-specific/i,
        /access-specific/i,
        /security-specific/i,
        /privacy-specific/i,
        /compliance-specific/i,
        /regulation-specific/i,
        /legal-specific/i,
        /terms-specific/i,
        /policy-specific/i,
        /guideline-specific/i,
        /best-practice-specific/i,
        /recommendation-specific/i,
        /suggestion-specific/i,
        /tip-specific/i,
        /trick-specific/i,
        /hack-specific/i,
        /shortcut-specific/i,
        /workaround-specific/i,
        /solution-specific/i,
        /fix-specific/i,
        /patch-specific/i,
        /update-specific/i,
        /upgrade-specific/i,
        /migration-specific/i,
        /integration-specific/i,
        /api-specific/i,
        /sdk-specific/i,
        /webhook-specific/i,
        /event-specific/i,
        /notification-specific/i,
        /alert-specific/i,
        /warning-specific/i,
        /error-specific/i,
        /exception-specific/i,
        /log-specific/i,
        /debug-specific/i,
        /trace-specific/i,
        /monitor-specific/i,
        /analytics-specific/i,
        /reporting-specific/i,
        /dashboard-specific/i,
        /metrics-specific/i,
        /kpi-specific/i,
        /goal-specific/i,
        /objective-specific/i,
        /target-specific/i,
        /benchmark-specific/i,
        /baseline-specific/i,
        /threshold-specific/i,
        /limit-specific/i,
        /quota-specific/i,
        /rate-specific/i,
        /frequency-specific/i,
        /interval-specific/i,
        /schedule-specific/i,
        /timing-specific/i,
        /duration-specific/i,
        /period-specific/i,
        /cycle-specific/i,
        /pattern-specific/i,
        /trend-specific/i,
        /seasonal-specific/i,
        /temporal-specific/i,
        /chronological-specific/i,
        /sequential-specific/i,
        /concurrent-specific/i,
        /parallel-specific/i,
        /synchronous-specific/i,
        /asynchronous-specific/i,
        /real-time-specific/i,
        /live-specific/i,
        /streaming-specific/i,
        /batch-specific/i,
        /bulk-specific/i,
        /mass-specific/i,
        /volume-specific/i,
        /scale-specific/i,
        /size-specific/i,
        /dimension-specific/i,
        /measurement-specific/i,
        /unit-specific/i,
        /format-specific/i,
        /structure-specific/i,
        /schema-specific/i,
        /model-specific/i,
        /template-specific/i,
        /pattern-specific/i,
        /framework-specific/i,
        /architecture-specific/i,
        /design-specific/i,
        /layout-specific/i,
        /style-specific/i,
        /theme-specific/i,
        /appearance-specific/i,
        /look-specific/i,
        /feel-specific/i,
        /user-experience-specific/i,
        /ux-specific/i,
        /ui-specific/i,
        /interface-specific/i,
        /dashboard-specific/i,
        /panel-specific/i,
        /control-specific/i,
        /settings-specific/i,
        /configuration-specific/i,
        /customization-specific/i,
        /personalization-specific/i,
        /tailoring-specific/i,
        /adaptation-specific/i,
        /modification-specific/i,
        /adjustment-specific/i,
        /tuning-specific/i,
        /optimization-specific/i,
        /improvement-specific/i,
        /enhancement-specific/i,
        /upgrade-specific/i,
        /update-specific/i,
        /refresh-specific/i,
        /renewal-specific/i,
        /restoration-specific/i,
        /reset-specific/i,
        /rebuild-specific/i,
        /reconstruction-specific/i,
        /reassembly-specific/i,
        /reinstallation-specific/i,
        /reconfiguration-specific/i,
        /recustomization-specific/i,
        /repersonalization-specific/i,
        /retailoring-specific/i,
        /readaptation-specific/i,
        /remodification-specific/i,
        /readjustment-specific/i,
        /retuning-specific/i,
        /reoptimization-specific/i,
        /reimprovement-specific/i,
        /reenhancement-specific/i,
        /reupgrade-specific/i,
        /reupdate-specific/i,
        /refreshing-specific/i,
        /renewing-specific/i,
        /restoring-specific/i,
        /resetting-specific/i,
      ],
      billing: [
        /billing/i,
        /payment/i,
        /charge/i,
        /cost/i,
        /price/i,
        /fee/i,
        /subscription/i,
        /plan/i,
        /tier/i,
        /package/i,
        /bundle/i,
        /deal/i,
        /offer/i,
        /promotion/i,
        /discount/i,
        /coupon/i,
        /voucher/i,
        /credit/i,
        /refund/i,
        /return/i,
        /exchange/i,
        /cancellation/i,
        /termination/i,
        /expiration/i,
        /renewal/i,
        /upgrade/i,
        /downgrade/i,
        /change/i,
        /modify/i,
        /adjust/i,
        /update/i,
        /edit/i,
        /remove/i,
        /delete/i,
        /cancel/i,
        /stop/i,
        /pause/i,
        /resume/i,
        /restart/i,
        /reactivate/i,
        /deactivate/i,
        /suspend/i,
        /unsuspend/i,
        /block/i,
        /unblock/i,
        /restrict/i,
        /unrestrict/i,
        /limit/i,
        /unlimit/i,
        /quota/i,
        /allowance/i,
        /usage/i,
        /consumption/i,
        /utilization/i,
        /efficiency/i,
        /effectiveness/i,
        /productivity/i,
        /output/i,
        /throughput/i,
        /capacity/i,
        /bandwidth/i,
        /latency/i,
        /response time/i,
        /load time/i,
        /render time/i,
        /processing time/i,
        /execution time/i,
        /runtime/i,
        /compile time/i,
        /build time/i,
        /deploy time/i,
        /startup time/i,
        /shutdown time/i,
        /idle time/i,
        /downtime/i,
        /uptime/i,
        /availability/i,
        /reliability/i,
        /stability/i,
        /consistency/i,
        /accuracy/i,
        /precision/i,
        /quality/i,
        /excellence/i,
        /perfection/i,
        /flawless/i,
        /seamless/i,
        /smooth/i,
        /fluid/i,
        /natural/i,
        /intuitive/i,
        /user-friendly/i,
        /accessible/i,
        /inclusive/i,
        /responsive/i,
        /adaptive/i,
        /flexible/i,
        /scalable/i,
        /extensible/i,
        /maintainable/i,
        /sustainable/i,
        /robust/i,
        /resilient/i,
        /durable/i,
        /long-lasting/i,
        /future-proof/i,
        /forward-compatible/i,
        /backward-compatible/i,
        /cross-platform/i,
        /multi-platform/i,
        /universal/i,
        /global/i,
        /international/i,
        /localized/i,
        /regional/i,
        /country-specific/i,
        /language-specific/i,
        /culture-specific/i,
        /timezone-specific/i,
        /currency-specific/i,
        /tax-specific/i,
        /shipping-specific/i,
        /payment-specific/i,
        /checkout-specific/i,
        /cart-specific/i,
        /inventory-specific/i,
        /order-specific/i,
        /customer-specific/i,
        /product-specific/i,
        /category-specific/i,
        /brand-specific/i,
        /store-specific/i,
        /merchant-specific/i,
        /admin-specific/i,
        /staff-specific/i,
        /role-specific/i,
        /permission-specific/i,
        /access-specific/i,
        /security-specific/i,
        /privacy-specific/i,
        /compliance-specific/i,
        /regulation-specific/i,
        /legal-specific/i,
        /terms-specific/i,
        /policy-specific/i,
        /guideline-specific/i,
        /best-practice-specific/i,
        /recommendation-specific/i,
        /suggestion-specific/i,
        /tip-specific/i,
        /trick-specific/i,
        /hack-specific/i,
        /shortcut-specific/i,
        /workaround-specific/i,
        /solution-specific/i,
        /fix-specific/i,
        /patch-specific/i,
        /update-specific/i,
        /upgrade-specific/i,
        /migration-specific/i,
        /integration-specific/i,
        /api-specific/i,
        /sdk-specific/i,
        /webhook-specific/i,
        /event-specific/i,
        /notification-specific/i,
        /alert-specific/i,
        /warning-specific/i,
        /error-specific/i,
        /exception-specific/i,
        /log-specific/i,
        /debug-specific/i,
        /trace-specific/i,
        /monitor-specific/i,
        /analytics-specific/i,
        /reporting-specific/i,
        /dashboard-specific/i,
        /metrics-specific/i,
        /kpi-specific/i,
        /goal-specific/i,
        /objective-specific/i,
        /target-specific/i,
        /benchmark-specific/i,
        /baseline-specific/i,
        /threshold-specific/i,
        /limit-specific/i,
        /quota-specific/i,
        /rate-specific/i,
        /frequency-specific/i,
        /interval-specific/i,
        /schedule-specific/i,
        /timing-specific/i,
        /duration-specific/i,
        /period-specific/i,
        /cycle-specific/i,
        /pattern-specific/i,
        /trend-specific/i,
        /seasonal-specific/i,
        /temporal-specific/i,
        /chronological-specific/i,
        /sequential-specific/i,
        /concurrent-specific/i,
        /parallel-specific/i,
        /synchronous-specific/i,
        /asynchronous-specific/i,
        /real-time-specific/i,
        /live-specific/i,
        /streaming-specific/i,
        /batch-specific/i,
        /bulk-specific/i,
        /mass-specific/i,
        /volume-specific/i,
        /scale-specific/i,
        /size-specific/i,
        /dimension-specific/i,
        /measurement-specific/i,
        /unit-specific/i,
        /format-specific/i,
        /structure-specific/i,
        /schema-specific/i,
        /model-specific/i,
        /template-specific/i,
        /pattern-specific/i,
        /framework-specific/i,
        /architecture-specific/i,
        /design-specific/i,
        /layout-specific/i,
        /style-specific/i,
        /theme-specific/i,
        /appearance-specific/i,
        /look-specific/i,
        /feel-specific/i,
        /user-experience-specific/i,
        /ux-specific/i,
        /ui-specific/i,
        /interface-specific/i,
        /dashboard-specific/i,
        /panel-specific/i,
        /control-specific/i,
        /settings-specific/i,
        /configuration-specific/i,
        /customization-specific/i,
        /personalization-specific/i,
        /tailoring-specific/i,
        /adaptation-specific/i,
        /modification-specific/i,
        /adjustment-specific/i,
        /tuning-specific/i,
        /optimization-specific/i,
        /improvement-specific/i,
        /enhancement-specific/i,
        /upgrade-specific/i,
        /update-specific/i,
        /refresh-specific/i,
        /renewal-specific/i,
        /restoration-specific/i,
        /reset-specific/i,
        /rebuild-specific/i,
        /reconstruction-specific/i,
        /reassembly-specific/i,
        /reinstallation-specific/i,
        /reconfiguration-specific/i,
        /recustomization-specific/i,
        /repersonalization-specific/i,
        /retailoring-specific/i,
        /readaptation-specific/i,
        /remodification-specific/i,
        /readjustment-specific/i,
        /retuning-specific/i,
        /reoptimization-specific/i,
        /reimprovement-specific/i,
        /reenhancement-specific/i,
        /reupgrade-specific/i,
        /reupdate-specific/i,
        /refreshing-specific/i,
        /renewing-specific/i,
        /restoring-specific/i,
        /resetting-specific/i,
      ],
    };

    // Smart routing configuration
    this.routingConfig = {
      setup: {
        primarySources: [
          "getting_started",
          "manual_getting_started",
          "helpcenter",
        ],
        secondarySources: ["api", "products", "orders"],
        promptTemplate: "setup-focused",
      },
      troubleshooting: [
        {
          primarySources: ["helpcenter", "forum", "api"],
          secondarySources: ["products", "orders", "theme"],
          promptTemplate: "troubleshooting-focused",
        },
      ],
      optimization: {
        primarySources: ["api", "products", "orders", "analytics"],
        secondarySources: ["theme", "helpcenter"],
        promptTemplate: "optimization-focused",
      },
      billing: {
        primarySources: ["helpcenter", "api"],
        secondarySources: ["getting_started"],
        promptTemplate: "billing-focused",
      },
    };
  }

  /**
   * Classify query intent using rule-based approach
   * @param {string} query - User query
   * @returns {Object} Classification result
   */
  classifyIntentRuleBased(query) {
    const queryLower = query.toLowerCase();
    const scores = {};

    // Calculate scores for each intent
    for (const [intent, patterns] of Object.entries(this.intentPatterns)) {
      scores[intent] = 0;
      for (const pattern of patterns) {
        if (pattern.test(queryLower)) {
          scores[intent]++;
        }
      }
    }

    // Find the intent with the highest score
    const maxScore = Math.max(...Object.values(scores));
    const primaryIntent = Object.keys(scores).find(
      (intent) => scores[intent] === maxScore
    );

    // Calculate confidence based on score distribution
    const totalScore = Object.values(scores).reduce(
      (sum, score) => sum + score,
      0
    );
    const confidence = totalScore > 0 ? maxScore / totalScore : 0;

    return {
      intent: primaryIntent || "general",
      confidence,
      scores,
      method: "rule-based",
    };
  }

  /**
   * Classify query intent using AI model
   * @param {string} query - User query
   * @returns {Object} Classification result
   */
  async classifyIntentAI(query) {
    try {
      const prompt = `Classify the following Shopify merchant query into one of these intents: setup, troubleshooting, optimization, billing, or general.

Query: "${query}"

Return your response in JSON format:
{
  "intent": "one of: setup, troubleshooting, optimization, billing, general",
  "confidence": 0.0-1.0,
  "reasoning": "brief explanation of why this intent was chosen",
  "keywords": ["key", "words", "that", "led", "to", "this", "classification"]
}`;

      const result = await this.model.generateContent({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
      });

      const response = result.response?.text();
      if (!response) {
        throw new Error("No response from AI model");
      }

      // Clean and parse JSON response
      let cleanedResponse = response.trim();

      // Remove markdown code blocks if present
      if (cleanedResponse.startsWith("```json")) {
        cleanedResponse = cleanedResponse
          .replace(/^```json\s*/, "")
          .replace(/\s*```$/, "");
      } else if (cleanedResponse.startsWith("```")) {
        cleanedResponse = cleanedResponse
          .replace(/^```\s*/, "")
          .replace(/\s*```$/, "");
      }

      // Parse JSON response
      const classification = JSON.parse(cleanedResponse);
      return {
        ...classification,
        method: "ai-based",
      };
    } catch (error) {
      console.error("AI classification error:", error);
      // Fallback to rule-based classification
      return this.classifyIntentRuleBased(query);
    }
  }

  /**
   * Classify query intent using hybrid approach
   * @param {string} query - User query
   * @returns {Object} Classification result
   */
  async classifyIntent(query) {
    // Get both rule-based and AI-based classifications
    const ruleBasedResult = this.classifyIntentRuleBased(query);
    const aiResult = await this.classifyIntentAI(query);

    // Combine results with weighted scoring
    const hybridConfidence =
      ruleBasedResult.confidence * 0.3 + aiResult.confidence * 0.7;

    // Use AI result as primary, but fallback to rule-based if AI confidence is low
    const finalIntent =
      aiResult.confidence > 0.6 ? aiResult.intent : ruleBasedResult.intent;
    const finalConfidence =
      aiResult.confidence > 0.6 ? hybridConfidence : ruleBasedResult.confidence;

    return {
      intent: finalIntent,
      confidence: finalConfidence,
      ruleBased: ruleBasedResult,
      aiBased: aiResult,
      method: "hybrid",
    };
  }

  /**
   * Get smart routing configuration for classified intent
   * @param {string} intent - Classified intent
   * @returns {Object} Routing configuration
   */
  getRoutingConfig(intent) {
    return (
      this.routingConfig[intent] ||
      this.routingConfig.general || {
        primarySources: ["helpcenter", "api"],
        secondarySources: ["getting_started"],
        promptTemplate: "general",
      }
    );
  }

  /**
   * Generate intent-specific prompt
   * @param {string} intent - Classified intent
   * @param {string} query - Original query
   * @param {Array} sources - Retrieved sources
   * @returns {string} Enhanced prompt
   */
  generateIntentSpecificPrompt(intent, query, sources) {
    const routingConfig = this.getRoutingConfig(intent);

    const intentPrompts = {
      setup: `You are helping a Shopify merchant with SETUP and CONFIGURATION. Focus on:
- Step-by-step instructions
- Prerequisites and requirements
- Best practices for initial setup
- Common setup mistakes to avoid
- Next steps after setup

Query: ${query}`,
      troubleshooting: `You are helping a Shopify merchant with TROUBLESHOOTING. Focus on:
- Identifying the root cause
- Providing specific solutions
- Common fixes and workarounds
- When to contact support
- Prevention strategies

Query: ${query}`,
      optimization: `You are helping a Shopify merchant with OPTIMIZATION. Focus on:
- Performance improvements
- Best practices for efficiency
- Advanced features and techniques
- Metrics and monitoring
- Scaling considerations

Query: ${query}`,
      billing: `You are helping a Shopify merchant with BILLING and PAYMENT. Focus on:
- Pricing and fee structures
- Payment processing options
- Subscription management
- Billing cycles and renewals
- Cost optimization strategies

Query: ${query}`,
      general: `You are helping a Shopify merchant with a general question. Provide comprehensive information covering:
- Basic concepts and explanations
- Related features and capabilities
- Additional resources and documentation
- Next steps and recommendations

Query: ${query}`,
    };

    return intentPrompts[intent] || intentPrompts.general;
  }

  /**
   * Get tool information
   * @returns {Object} Tool metadata
   */
  getToolInfo() {
    return {
      name: "intent_classification",
      description:
        "Classify merchant queries into setup, troubleshooting, optimization, billing, or general intents",
      capabilities: [
        "Rule-based pattern matching",
        "AI-powered classification",
        "Hybrid classification approach",
        "Smart routing configuration",
        "Intent-specific prompt generation",
      ],
      intents: [
        "setup",
        "troubleshooting",
        "optimization",
        "billing",
        "general",
      ],
      examples: [
        "How do I set up my Shopify store? (setup)",
        "My store is not loading properly (troubleshooting)",
        "How can I improve my store performance? (optimization)",
        "What are the pricing plans for Shopify? (billing)",
        "Tell me about Shopify features (general)",
      ],
    };
  }
}

export default IntentClassificationService;
